### ISSUE TITLE
Problem with pod

### ISSUE THREAD

**Issue by boardmain** [eventtus/photo-editor#15]
hi if i try to install it from pod
in the resource directory  i see the xib file and not the storyboard
so the 
~~~
let photoEditor = UIStoryboard(name: "PhotoEditor", bundle: Bundle(for: PhotoEditorViewController.self)).instantiateViewController(withIdentifier: "PhotoEditorViewController") as! PhotoEditorViewController
~~~

fail

**Comment by mhm-ibrahim** [comment]
@boardmain 
The Example was V 0.3 that's why it was different 
in V 0.5  it works like this 
~~~
let photoEditor = PhotoEditorViewController(nibName:"PhotoEditorViewController",bundle: Bundle(for: PhotoEditorViewController.self))
~~~
I updated the example 
latest updates are on this fork https://github.com/m-hamed/photo-editor

**Comment by boardmain** [comment]
ah ok thank you fantastic

and another question
how can i increase the pan area for the sticker? if i reduce it is not easy to resize when sticker are small, how i can create a margin area ? ( i see you recognize it with alpha > 0 )

**Comment by mhm-ibrahim** [comment]
both features contradicts with each other 
sadly for now you can't have both 
I'll try to come up with a solution soon
